# Generated by Django 3.1.5 on 2021-06-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCore', '0003_auto_20210610_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='tipoNoticia',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
