# Generated by Django 3.1.5 on 2021-06-10 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCore', '0004_noticia_tiponoticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('idJugador', models.AutoField(primary_key=True, serialize=False)),
                ('pnombre', models.CharField(max_length=50, verbose_name='Primer nombre')),
                ('snombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo nombre')),
                ('apaterno', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('amaterno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido materno')),
                ('nacimiento', models.CharField(max_length=50, verbose_name='Lugar de nacimiento')),
                ('fechaNacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('estilo', models.CharField(max_length=50, verbose_name='Estilo de juego')),
                ('preInf', models.CharField(max_length=50, verbose_name='Preinfantil')),
                ('inf', models.CharField(max_length=50, verbose_name='Infantil')),
                ('juvenil', models.CharField(max_length=50, verbose_name='Juvenil')),
                ('tc', models.CharField(max_length=50, verbose_name='Todo competidor')),
            ],
            options={
                'verbose_name': 'jugador',
                'verbose_name_plural': 'jugadores',
            },
        ),
        migrations.CreateModel(
            name='ImagenJugador',
            fields=[
                ('idImagenJug', models.AutoField(primary_key=True, serialize=False)),
                ('imagenJug', models.ImageField(upload_to='home')),
                ('fkJugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCore.jugador')),
            ],
            options={
                'verbose_name': 'imagenJugador',
                'verbose_name_plural': 'imagenesJugador',
            },
        ),
    ]
