# Generated by Django 3.1.5 on 2021-06-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCore', '0005_imagenjugador_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenjugador',
            name='alt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='alt'),
        ),
        migrations.AddField(
            model_name='imagenjugador',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='title'),
        ),
    ]
