# Generated by Django 3.1.5 on 2021-06-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCore', '0006_auto_20210610_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='imagenPortada',
            field=models.ImageField(blank=True, null=True, upload_to='home'),
        ),
    ]
