# Generated by Django 3.1.5 on 2021-06-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCore', '0007_jugador_imagenportada'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='categoria',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Categoria actual'),
        ),
    ]
