# Generated by Django 3.1.5 on 2021-06-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCore', '0008_jugador_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='imagenPortada',
            field=models.ImageField(upload_to='home'),
        ),
    ]
