# Generated by Django 3.1.5 on 2021-06-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCore', '0009_auto_20210614_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='genero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Genero'),
        ),
    ]
