# Generated by Django 3.1.5 on 2021-06-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCore', '0010_jugador_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='genero',
            field=models.CharField(max_length=10, verbose_name='Genero'),
        ),
    ]
