# Generated by Django 3.1.5 on 2021-06-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCore', '0011_auto_20210617_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dirigente',
            fields=[
                ('id_dirigente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('cargo', models.CharField(max_length=60)),
                ('club', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'dirigente',
                'verbose_name_plural': 'dirigentes',
            },
        ),
    ]
